name: Run Bench
on:
 workflow_dispatch:
jobs:
  bench:
    name: bench
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    container:
      image: georust/geo-ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Bench baseline
        run: cargo bench
      - run: git checkout ${{ github.sha }}
      - name: Bench changes
        run: cargo bench

